feat: added fair launch claim
Geo-Web-Project/cadastre pull request #135
Opened 2022-05-23 01:43 UTC by zhyd1997

Close: #101

2022-05-23 06:56 UTC, zhyd1997 commented
Hi, @codynhat 

Why did I get `_auctionStart` and `_auctionEnd` both `0`:
```js
  const _auctionStart = await claimerContract.auctionStart(); // 0
  const _auctionEnd = await claimerContract.auctionEnd();     // 0
```

2022-05-23 22:45 UTC, zhyd1997 commented
> The current deployment has them set to 0. But we can change it. Do you need me to change it for testing?

Got it, no need to change it, I can handle this situation.

2022-05-25 02:01 UTC, zhyd1997 commented
Hi, @codynhat 

2 questions:

### a. what's the `block` here:

https://github.com/Geo-Web-Project/core-contracts/blob/bb6b1d0e12c03615e1ab21dc7d5e6d19abfb9cc4/contracts/FairLaunchClaimer.sol#L84

### b. and the `Claim` action needs to do the **same** thing with **Simple Claim View**?

2022-05-27 20:43 UTC, codynhat requested changes

2022-05-27 20:43 UTC, codynhat commented on components/Sidebar.tsx
> +          auctionEnd="32376137040000"
Should this be `auctionEnd`?

2022-05-27 20:43 UTC, codynhat commented on components/Sidebar.tsx
> +  console.log("requiredBid: ------->: ", requiredBid);
Can you remove the console.log before merging?

2022-05-27 20:43 UTC, codynhat commented on components/cards/FairLaunchInfo.tsx
> +            Time Remaining: <span>{duration.days()}</span>:
Is there a way to add zeros for padding?

For example, the time currently shows `5:7:17:8`. Could this be -> `5:07:17:08`?

2022-05-27 21:51 UTC, codynhat approved these changes
LGTM!

2022-05-27 21:51 UTC, merged