add copy token widget
Geo-Web-Project/cadastre pull request #184
Opened 2022-07-02 09:08 UTC by Nikitachr

2022-07-02 20:02 UTC, gravenp commented on components/wrap/WrapModal.tsx
> +    decimals: 16,
# of decimals should be 18

2022-07-02 20:09 UTC, gravenp requested changes
ETHx token should have 18 decimals (currently being added as 16). 

Also, the widget is extended beyond the edge of the modal and shifts locations as the width of the ETHx balance changes. Can you expand the size of the modal to fit the widget and fix its location within the modal rather than placing it relative to the end of the ETHx balance element? 
<img width="488" alt="Screen Shot 2022-07-02 at 2 04 52 PM" src="https://user-images.githubusercontent.com/15019279/177014809-d6d06d11-b424-421e-8955-7a40a03850a6.png">

2022-07-05 16:18 UTC, gravenp approved these changes
Changes look great! Thanks @Nikitachr!

@codynhat you can merge this if it looks good to you.

2022-07-06 17:14 UTC, codynhat approved these changes

2022-07-06 17:19 UTC, merged