feat: add min for sale price requirement
Geo-Web-Project/cadastre pull request #276
Opened 2022-10-20 11:10 UTC by tnrdd

# Description

Require minimum for sale price requirement for claim, edit and reclaim transactions.

# Issue

fixes #253 

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Alert Reviewers

@codynhat @gravenp

2022-10-20 18:52 UTC, codynhat approved these changes

2022-10-20 21:48 UTC, gravenp requested changes
Functionality per the ticket all looks great. Thanks, @tnrdd. 

Just a couple of changes to the copy that I added in line (my bad!). 

We are handling Foreclosure Auction Claims that drop below the min price differently than how it's displaying on the Cadastre currently, but I'll create a separate ticket for that.

2022-10-20 21:48 UTC, gravenp commented on components/cards/ActionForm.tsx
>                    For Sale Price must be a number greater than{" "}
Can this text read: `For Sale Price must be greater than or equal to {" "}`

2022-10-20 21:48 UTC, gravenp commented on components/cards/ActionForm.tsx
>                        You'll have 7 days to accept or reject any bid that meets
Can we change the text here to `You'll have 7 days to accept or reject any bid that meets your price.`?

The change here is just from "this" to "your" price.

2022-10-21 14:47 UTC, gravenp commented on components/cards/ActionForm.tsx
>                    For Sale Price must be a number greater than{" "}
Looks good. TY

2022-10-21 14:48 UTC, gravenp commented on components/cards/ActionForm.tsx
>                        You'll have 7 days to accept or reject any bid that meets
Thanks!

2022-10-21 16:47 UTC, codynhat approved these changes

2022-10-21 16:47 UTC, merged