feat: add URL based parcel navigation
Geo-Web-Project/cadastre pull request #361
Opened 2023-01-05 15:49 UTC by tnrdd

# Description

-Setting `latitude`, `longitude` and `id` query params will jump to the corresponding parcel on map load.
In the parcel panel the user can copy a ready made URL with the corresponding query params to share around or for later use.
-Disable map rotation to avoid accidental drag/touchpad reorientations.

# Issue

fixes #359, fixes #360 

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Additional comments

-When the content of the Bootstrap tooltip is changed (in this case switching from "Copy link to Parcel" to "Link Copied") to have a shorter or longer text the new tooltip is out of position because [the old position is not updated](https://github.com/react-bootstrap/react-bootstrap/issues/5971#issuecomment-899512817).
-Since Bootstrap 5 using a click event to trigger the tooltip [will ignore the `delay` prop](https://react-bootstrap.github.io/components/overlays/#overlay-trigger-props), this prop is an object with an `hide` field used to hide the tooltip after a number of milliseconds.
We are currently depending on the old behaviour in `CopyTokenAddress` component where clicking on it triggered the tooltip to show with the content text "Copied" for 4 seconds before being hidden, now when the user clicks on it the tooltip is never hidden until a subsequent click.

To deal with these issues a `CopyTooltip` component is added in this PR to be used for copying the parcel link, by `CopyTokenAddress` and possible future components that might need it.

# Alert Reviewers

@codynhat @gravenp

2023-01-05 20:38 UTC, gravenp requested changes
The linking functionality is looking good! Disabling the rotation also is gtg. Thanks @tnrdd.

Two  requests:
- Could we set the zoom to the parcel upon opening the link to be one level higher up?
- Let's shrink the link & open browser icons just a bit and have the right side of the link icon align with the X icon in the top right of that section. See the screenshot below for reference.

<img width="435" alt="Screenshot 2023-01-05 at 1 35 15 PM" src="https://user-images.githubusercontent.com/15019279/210875344-4de29e83-74ce-45d8-a379-1529a2c5768a.png">

2023-01-06 09:24 UTC, tnrdd commented
> Could we set the zoom to the parcel upon opening the link to be one level higher up?
> 
With latest push the zoom was set one level higher for the parcel navigation both from link and from the portfolio modal.
Is that alright or do we want to be a little more zoomed in the portfolio modal case?

2023-01-06 15:45 UTC, gravenp approved these changes
The zoom on link and from the profile dashboard both look good to me. Icon sizing/placement are good as well.

Thanks, @tnrdd! Ready for you @codynhat

2023-01-09 16:28 UTC, codynhat approved these changes

2023-01-09 16:28 UTC, merged